language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite
  - DB=postgresql
before_script:
- psql -c 'create database visualstats_test' -U postgres
script: 
- RAILS_ENV=test bundle exec rake --trace db:schema:load
- RAILS_ENV=test bundle exec rspec spec
matrix:
  allow_failures:
    - rvm: 2.0.0
notifications:
  webhooks:
  - http://visualstats.herokuapp.com/bkleinen/VisualStats/notify

