require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuildCompactsController do

  # This should return the minimal set of attributes required to create a valid
  # BuildCompact. As you add validations to BuildCompact, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "result" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuildCompactsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all build_compacts as @build_compacts" do
      build_compact = BuildCompact.create! valid_attributes
      get :index, {}, valid_session
      assigns(:build_compacts).should eq([build_compact])
    end
  end

  describe "GET show" do
    it "assigns the requested build_compact as @build_compact" do
      build_compact = BuildCompact.create! valid_attributes
      get :show, {:id => build_compact.to_param}, valid_session
      assigns(:build_compact).should eq(build_compact)
    end
  end

  describe "GET new" do
    it "assigns a new build_compact as @build_compact" do
      get :new, {}, valid_session
      assigns(:build_compact).should be_a_new(BuildCompact)
    end
  end

  describe "GET edit" do
    it "assigns the requested build_compact as @build_compact" do
      build_compact = BuildCompact.create! valid_attributes
      get :edit, {:id => build_compact.to_param}, valid_session
      assigns(:build_compact).should eq(build_compact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BuildCompact" do
        expect {
          post :create, {:build_compact => valid_attributes}, valid_session
        }.to change(BuildCompact, :count).by(1)
      end

      it "assigns a newly created build_compact as @build_compact" do
        post :create, {:build_compact => valid_attributes}, valid_session
        assigns(:build_compact).should be_a(BuildCompact)
        assigns(:build_compact).should be_persisted
      end

      it "redirects to the created build_compact" do
        post :create, {:build_compact => valid_attributes}, valid_session
        response.should redirect_to(BuildCompact.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved build_compact as @build_compact" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuildCompact.any_instance.stub(:save).and_return(false)
        post :create, {:build_compact => { "result" => "invalid value" }}, valid_session
        assigns(:build_compact).should be_a_new(BuildCompact)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuildCompact.any_instance.stub(:save).and_return(false)
        post :create, {:build_compact => { "result" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested build_compact" do
        build_compact = BuildCompact.create! valid_attributes
        # Assuming there are no other build_compacts in the database, this
        # specifies that the BuildCompact created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BuildCompact.any_instance.should_receive(:update_attributes).with({ "result" => "1" })
        put :update, {:id => build_compact.to_param, :build_compact => { "result" => "1" }}, valid_session
      end

      it "assigns the requested build_compact as @build_compact" do
        build_compact = BuildCompact.create! valid_attributes
        put :update, {:id => build_compact.to_param, :build_compact => valid_attributes}, valid_session
        assigns(:build_compact).should eq(build_compact)
      end

      it "redirects to the build_compact" do
        build_compact = BuildCompact.create! valid_attributes
        put :update, {:id => build_compact.to_param, :build_compact => valid_attributes}, valid_session
        response.should redirect_to(build_compact)
      end
    end

    describe "with invalid params" do
      it "assigns the build_compact as @build_compact" do
        build_compact = BuildCompact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuildCompact.any_instance.stub(:save).and_return(false)
        put :update, {:id => build_compact.to_param, :build_compact => { "result" => "invalid value" }}, valid_session
        assigns(:build_compact).should eq(build_compact)
      end

      it "re-renders the 'edit' template" do
        build_compact = BuildCompact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuildCompact.any_instance.stub(:save).and_return(false)
        put :update, {:id => build_compact.to_param, :build_compact => { "result" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested build_compact" do
      build_compact = BuildCompact.create! valid_attributes
      expect {
        delete :destroy, {:id => build_compact.to_param}, valid_session
      }.to change(BuildCompact, :count).by(-1)
    end

    it "redirects to the build_compacts list" do
      build_compact = BuildCompact.create! valid_attributes
      delete :destroy, {:id => build_compact.to_param}, valid_session
      response.should redirect_to(build_compacts_url)
    end
  end

end
